import AppKit
import Foundation

/// A copy of everything that was on the pasteboard, per item, per
/// representation. Lazy or promised types that refuse to hand over their data
/// are the one thing this cannot preserve.
public struct ClipboardSnapshot: Equatable, Sendable {
    public var items: [[String: Data]]

    public init(items: [[String: Data]] = []) {
        self.items = items
    }
}

public struct PasteboardToken: Equatable, Sendable {
    public var changeCount: Int
    public var writtenString: String
}

public struct ClipboardWrite: Sendable {
    public var token: PasteboardToken
    public var snapshot: ClipboardSnapshot
}

public enum ClipboardTransaction {
    static let transientTypes = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.fennec.transient",
    ]

    public static func capture(_ pasteboard: NSPasteboard) -> ClipboardSnapshot {
        let items = (pasteboard.pasteboardItems ?? []).map { item -> [String: Data] in
            var representations: [String: Data] = [:]
            for type in item.types {
                if let data = item.data(forType: type) {
                    representations[type.rawValue] = data
                }
            }
            return representations
        }
        return ClipboardSnapshot(items: items)
    }

    public static func write(_ text: String, to pasteboard: NSPasteboard) -> ClipboardWrite {
        let snapshot = capture(pasteboard)
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        for type in transientTypes {
            item.setData(Data(), forType: NSPasteboard.PasteboardType(type))
        }
        pasteboard.writeObjects([item])
        let token = PasteboardToken(changeCount: pasteboard.changeCount, writtenString: text)
        return ClipboardWrite(token: token, snapshot: snapshot)
    }

    /// Put the previous contents back, but only when nothing has touched the
    /// pasteboard since our write.
    @discardableResult
    public static func restore(_ write: ClipboardWrite, to pasteboard: NSPasteboard) -> Bool {
        let shouldRestore = ClipboardGuard.shouldRestore(
            ourChangeCount: write.token.changeCount,
            ourString: write.token.writtenString,
            currentChangeCount: pasteboard.changeCount,
            currentString: pasteboard.string(forType: .string)
        )
        guard shouldRestore else { return false }
        pasteboard.clearContents()
        if !write.snapshot.items.isEmpty {
            let items = write.snapshot.items.map { representations -> NSPasteboardItem in
                let item = NSPasteboardItem()
                for (rawType, data) in representations {
                    item.setData(data, forType: NSPasteboard.PasteboardType(rawType))
                }
                return item
            }
            pasteboard.writeObjects(items)
        }
        return true
    }
}
