import AppKit
import CoreGraphics
import Foundation

public actor Injector {
    private static let transientTypes = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.fennec.transient",
    ]

    public init() {}

    public func paste(_ text: String, autoSend: Bool) async {
        let pasteboard = NSPasteboard.general
        let previousString = pasteboard.string(forType: .string)

        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        for type in Self.transientTypes {
            item.setData(Data(), forType: NSPasteboard.PasteboardType(type))
        }
        pasteboard.writeObjects([item])
        let ourChangeCount = pasteboard.changeCount

        try? await Task.sleep(nanoseconds: 100_000_000)
        postKey(keyCode: 9, flags: .maskCommand)
        if autoSend {
            try? await Task.sleep(nanoseconds: 150_000_000)
            postKey(keyCode: 36, flags: [])
        }
        try? await Task.sleep(nanoseconds: 150_000_000)

        let restore = ClipboardGuard.shouldRestore(
            ourChangeCount: ourChangeCount,
            ourString: text,
            currentChangeCount: pasteboard.changeCount,
            currentString: pasteboard.string(forType: .string)
        )
        if restore {
            pasteboard.clearContents()
            if let previousString {
                pasteboard.setString(previousString, forType: .string)
            }
        }
    }

    private func postKey(keyCode: CGKeyCode, flags: CGEventFlags) {
        guard let source = CGEventSource(stateID: .privateState) else { return }
        let down = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: true)
        let up = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: false)
        down?.flags = flags
        up?.flags = flags
        down?.post(tap: .cghidEventTap)
        up?.post(tap: .cghidEventTap)
    }
}
